# Generated by Django 3.1.7 on 2021-02-21 16:17

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=upload.models.Image.get_file_path, validators=[upload.models.Image.validate_image])),
            ],
        ),
    ]
